<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="FluentValidation" Version="11.10.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/BackendTemplate.Domain/BackendTemplate.Domain.csproj" />
  </ItemGroup>
</Project>
